version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12.x
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - cd ./frontend
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - "**/*"
  base-directory: frontend/build
